#version: '3.8'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: requirements/mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
      - wp_super_password
    volumes:
      - mariadb:/var/lib/mysql
    command: /bin/bash -c "/tmp/init-db.sh"
    stdin_open: true  # Required to keep stdin open
    tty: true         # Allocates a pseudo-TTY
    #command: mysqld_safe --skip-grant-tables  # <-- Add this line temporarily
    restart: unless-stopped
    healthcheck:
       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
       interval: 5s
       timeout: 5s
       retries: 5

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build: requirements/nginx
    env_file:
      - .env
    volumes: 
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"   # Expose le port HTTPS pour accès externe
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    build: requirements/wordpress
    env_file:
      - .env
    secrets:
      - wp_super_password
      - wp_random_password
      - db_password
    volumes: 
      - wordpress:/var/www/wordpress
    ports:
      - "9000"    # WordPress tourne sur le port 9000 pour PHP-FPM
    command: /bin/bash -c "/usr/local/bin/wp-setup.sh"
    stdin_open: true  # Required to keep stdin open
    tty: true         # Allocates a pseudo-TTY
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/user/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/user/data/mariadb'

networks:
  inception:
    name: inception
    driver: bridge  # Tous les services partagent ce réseau pour communiquer

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_super_password:
    file: ../secrets/wp_super_password.txt
  wp_random_password:
    file: ../secrets/wp_random_password.txt
