version: '3.8'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception # network auquel il appartient
    build: requirements/mariadb  # instruction pour construire le docker (ou trouver dockerfile etc)
    env_file: .env #le fichier d'environnement pour transmettre les variables
    secrets:
      - sql_password
      - sql_root_password
    environment:
      SQL_PASSWORD: /run/secrets/sql_password
      SQL_ROOT_PASSWORD: /run/secrets/sql_root_password
    volumes: 
      - mariadb:/var/lib/mysql
    restart: unless-stopped  # redémarre tant qu'il n'est pas stoppé 
    expose:  # le port interne à exposer sans le mapper à l'hôte
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on: #indique de ne pas démarrer nginx tant que wp n'a pas démarré
      - wordpress
    build: requirements/nginx
    env_file: .env
    volumes: 
      - wordpress:/var/www/wordpress
    ports:
      - "443:443" # on indique le port qui sera exposé a la machine locale
    restart: on-failure  #redémarrer a uniquement en cas de crash.

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - wp_boss_password
      - wp_random_password
      - sql_password
    environment:
      WP_ADMIN_PASSWORD: /run/secrets/wp_boss_password
      WP_SECOND_USER_PASSWORD: /run/secrets/wp_random_password
      SQL_PASSWORD: /run/secrets/sql_password
    volumes: 
      - wordpress:/var/www/wordpress
    ports:
      - "9000"
    restart: on-failure

volumes:
  wordpress:
    driver: local #stocker le volume en local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/login/data/wordpress' #ou stocker le dossier en local
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'	 # ?? à quoi ca sert?
      device: '/Users/login/data/mariadb'

networks:
    inception:
    driver: bridge #bridge=défaut, cela permet de ne pas isoler les container
                   #et de leur permettre de communiquet entre eux
					
