#version: '3.8'
#n'est visiblement plus nécessaire retiré à cause warning en construisant

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: requirements/mariadb
    image: mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
      - wp_super_password
    volumes:
      - mariadb:/var/lib/mysql
    command: /bin/bash -c "/tmp/init-db.sh"
    stdin_open: true  # Required to keep stdin open//enlever ?
    tty: true         # Allocates a pseudo-TTY//enlever ?
    restart: unless-stopped
    healthcheck: #ping mariadb régulièrement pour vérifier si actif et éviter que wp n'essaie de se connecter trop tôt
       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
       interval: 5s
       timeout: 5s
       retries: 5

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build: requirements/nginx
    image: nginx
    env_file:
      - .env
    volumes: 
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"   #expose le port HTTPS
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    build: requirements/wordpress
    image: wordpress
    env_file:
      - .env
    secrets:
      - wp_super_password
      - wp_random_password
      - db_password
    volumes: 
      - wordpress:/var/www/wordpress
    ports:
      - "9000"    # Worwp tourne sur le port 9000 pour PHP-FPM (FastCGI Process Manager)
    command: /bin/bash -c "/usr/local/bin/wp-setup.sh"
    stdin_open: true  # Required to keep stdin open//enlever ?
    tty: true         # Allocates a pseudo-TTY//enlever ?
    restart: on-failure

#local=stocké localement sur le système hote
#o=option de montage du volume
#bind=créé une liaison (bind mount) entre un répertoire de l'hote et le conteneur
#cela permet de mieux communiquer avec l'hote
#avantage volumes : persistance des données 
volumes:
  wordpress:
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/user/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/user/data/mariadb'

networks:
  inception:
    name: inception
    driver: bridge  # les services partagent ce réseau pour communiquer

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_super_password:
    file: ../secrets/wp_super_password.txt
  wp_random_password:
    file: ../secrets/wp_random_password.txt
